### ISSUE TITLE
defaultJobOwner not taking effect

### ISSUE THREAD

**Issue by viddygit** [mesos/chronos#95]
I'm configuring the installation of Chronos, and by default when creating a new job, the owner is set to "ateam@airbnb.com."

According to the docs (https://github.com/airbnb/chronos/tree/master/config#defaultjobowner), we should be able to override this by setting the defaultJobOwner config setting in the yml config file.  That does not appear to be working...

The contents of my config file are below:

```
root@ip-10-1-0-245:/opt/chronos# cat /etc/chronos/config.yml 
mailUser: "[secret]"
mailPassword: "[secret]"
mailServer: "email-smtp.us-east-1.amazonaws.com:25"
mailFrom: "cron-alerts@mydomain.com"
mailSslOn: true
defaultJobOwner:  "changeme@mydomain.com"
scheduleHorizonSeconds: 60
master: local

http:

    adminPort: 4401
    port: 4400
    rootPath: "/scheduler/*"

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

```
